### ISSUE TITLE
Passing arguments

### ISSUE THREAD

**Issue by nswathi10** [AlbertoLanaro/ImagePatchExtractor#1]
I run the code with following arguments 
! python /content/ImagePatchExtractor/patch_extractor.py -i /content/drive/My Drive/First50_Set1_Swathi/dcm2png/ -s 50,50
but i get an error as 
patch_extractor.py: error: unrecognized arguments: Drive/First50_Set1_Swathi/dcm2png/
also i get an error as
patch_extractor.py: error: argument -s/--patch_size: invalid int value: '50,50'
please help me out , very much in need of it

**Comment by AlbertoLanaro** [comment]
Hi, sorry for the delay. In order to specify the size of the patches to be extracted you need just to pass a single integer. In your case it will be 
`python /content/ImagePatchExtractor/patch_extractor.py -i /content/drive/My\ Drive/First50_Set1_Swathi/dcm2png/ -s 50`

**Comment by nswathi10** [comment]
Thanks a lot for helping me.
